version: '3'
services:
  
  mysqldb:
    image: mysql:8.0
    container_name: app_mysql
    ports:
      - 3308:3306
    volumes:
      - hw_db_data:/var/lib/mysql
      - ./datastorage/mysql/scripts/sql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hlm_db
      - MYSQL_USER=hlm_admin
      - MYSQL_PASSWORD=hlm_admin

volumes:
  hw_db_data: {}

networks:
    default:
        external:
            name: my-local
