version: '3'
services:
  
  adminer:
    image: adminer
    container_name: app_adminer
    restart: always
    ports:
      - 8088:8080

volumes:
  hw_db_data: {}

networks:
    default:
        external:
            name: my-local
