# Use root/exampleRoot as user/password credentials
version: '2'

services:

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      
      # - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3310:3306
    volumes:
      - ./mysqldata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
