version: '2'
services:
  web:
    image: gitea/gitea:1.3.2
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=localgit
      - MYSQL_USER=localgit
      - MYSQL_PASSWORD=localgit
    volumes:
      - ./db/:/var/lib/mysql
